### ISSUE TITLE
Ansible on OMD 4.40 throws errors

### ISSUE THREAD

**Issue by infraweavers** [ConSol/omd#141]
We're going to be upgrading to 4.60 at some point, however we noticed that when we push ansible we get these errors. Pretty sure it's some sort of incompatibility between the system python and the included Ansible.

```
[WARNING]: Skipping plugin (/omd/sites/default/lib/python/ansible/plugins/connection/docker.py) as it seems to be invalid: No module named 'distutils.spawn'
[WARNING]: Skipping plugin (/omd/sites/default/lib/python/ansible/plugins/connection/iocage.py) as it seems to be invalid: No module named 'distutils.spawn'
[WARNING]: Skipping plugin (/omd/sites/default/lib/python/ansible/plugins/connection/jail.py) as it seems to be invalid: No module named 'distutils.spawn'
[WARNING]: Skipping plugin (/omd/sites/default/lib/python/ansible/plugins/connection/kubectl.py) as it seems to be invalid: No module named 'distutils.spawn'
[WARNING]: Skipping plugin (/omd/sites/default/lib/python/ansible/plugins/connection/libvirt_lxc.py) as it seems to be invalid: No module named 'distutils.spawn'
[WARNING]: Skipping plugin (/omd/sites/default/lib/python/ansible/plugins/connection/lxd.py) as it seems to be invalid: No module named 'distutils.spawn'
[WARNING]: Skipping plugin (/omd/sites/default/lib/python/ansible/plugins/connection/oc.py) as it seems to be invalid: No module named 'distutils.spawn'
/omd/sites/default/lib/python/pyvmomi-6.7.1.2018.12-py3.9.egg/pyVmomi/Version.py:26: SyntaxWarning: "is" with a literal. Did you mean "=="?
/omd/sites/default/lib/python/pyvmomi-6.7.1.2018.12-py3.9.egg/pyVmomi/Version.py:26: SyntaxWarning: "is" with a literal. Did you mean "=="?
[WARNING]: Skipping plugin (/omd/sites/default/lib/python/ansible/plugins/connection/zone.py) as it seems to be invalid: No module named 'distutils.spawn'
[WARNING]: Skipping plugin (/omd/sites/default/lib/python/ansible/plugins/callback/osx_say.py) as it seems to be invalid: No module named 'distutils.spawn'
[WARNING]: Skipping plugin (/omd/sites/default/lib/python/ansible/plugins/callback/say.py) as it seems to be invalid: No module named 'distutils.spawn'
```

**Comment by sni** [comment]
Some more details would be great. What OS is that? What command did you run and is there anything python related in your environment?

**Comment by infraweavers** [comment]
Apologies, I hit enter too soon and forgot to apply the useful info ¬_¬

We're pretty sure this started happening when we upgraded to Debian 11 from Debian 10

We have a single OMD site called "default" and the command is run as the user "default".

The command was like:
`ansible-playbook --user infrastructure --ask-pass --ask-become-pass --inventory=hosts --limit=SERVERNAME site.yml`


There's nothing/very little in this environment; it's a dedicated OMD server. I've attached the output of `dpkg --get-selections`.
I am 99.9% sure there's nothing special to do with python in the environment now I've had a look.
[dpkg_selections.txt](https://github.com/ConSol/omd/files/9733054/dpkg_selections.txt)

**Comment by sni** [comment]
seems to be an issue in the shipped library. It has been fixed in
https://github.com/vmware/pyvmomi/commit/7802b64a5efca695001fe55fb77e7cc849476885
i will apply that patch since i don't want to do a major update on that library.

**Comment by infraweavers** [comment]
Just test-upgraded to OMD 5.0 and it appears this is still happening. Not sure if that fits with your expectations or not

```
[WARNING]: Skipping plugin (/omd/sites/default/lib/python/ansible/plugins/connection/docker.py) as it seems to be
invalid: No module named 'distutils.spawn'
[WARNING]: Skipping plugin (/omd/sites/default/lib/python/ansible/plugins/connection/iocage.py) as it seems to be
invalid: No module named 'distutils.spawn'
[WARNING]: Skipping plugin (/omd/sites/default/lib/python/ansible/plugins/connection/jail.py) as it seems to be
invalid: No module named 'distutils.spawn'
[WARNING]: Skipping plugin (/omd/sites/default/lib/python/ansible/plugins/connection/kubectl.py) as it seems to be
invalid: No module named 'distutils.spawn'
[WARNING]: Skipping plugin (/omd/sites/default/lib/python/ansible/plugins/connection/libvirt_lxc.py) as it seems to be
invalid: No module named 'distutils.spawn'
[WARNING]: Skipping plugin (/omd/sites/default/lib/python/ansible/plugins/connection/lxd.py) as it seems to be invalid:
No module named 'distutils.spawn'
[WARNING]: Skipping plugin (/omd/sites/default/lib/python/ansible/plugins/connection/oc.py) as it seems to be invalid:
No module named 'distutils.spawn'
[WARNING]: Skipping plugin (/omd/sites/default/lib/python/ansible/plugins/connection/zone.py) as it seems to be
invalid: No module named 'distutils.spawn'
[WARNING]: Skipping plugin (/omd/sites/default/lib/python/ansible/plugins/callback/osx_say.py) as it seems to be
invalid: No module named 'distutils.spawn'
[WARNING]: Skipping plugin (/omd/sites/default/lib/python/ansible/plugins/callback/say.py) as it seems to be invalid:
No module named 'distutils.spawn'
```

![image](https://user-images.githubusercontent.com/36475663/216346184-810d1499-8fc9-47f4-9905-d51b89cdb673.png)

**Comment by lausser** [comment]
Can you install the package python3-distutils and check if the error has gone then?

**Comment by infraweavers** [comment]
Yep that does silence the errors
